# Generated by Django 4.2.26 on 2025-12-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
