# Generated by Django 4.2.26 on 2025-12-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_inventoryitem_amount_inventoryitem_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
