# Generated by Django 4.2.26 on 2025-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Employee'), (1, 'Manager'), (2, 'Admin')], default=2),
        ),
    ]
